[package]
name = "utf7-imap"
version = "0.2.0"
authors = ["Ilya Medvedev <ilya@medvedev.im>"]
license = "MIT"
homepage = "https://github.com/iam-medvedev/rust-utf7-imap"
repository = "https://github.com/iam-medvedev/rust-utf7-imap"
description = "Mailbox names decoder (UTF-7 IMAP RFC 3501)"
keywords = ["mailbox", "decoder", "utf7", "imap", "rfc3501"]
categories = ["parsing","encoding"]
readme = "README.md"
maintenance = { status = "experimental" }

[dependencies]
regex = "1.5"
base64 = "0.13"
encoding_rs = "0.8"
